version: "3.8"

services:
  server-test:
    build: .
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    depends_on:
      - db-test
    volumes:
      - .:/app
    command: bash -c "
      npm run test:prisma
      && npx dotenv -e .env.test -- npm start
      & npx wait-on ${API_URL:-http://server-test:3001}
      && npx dotenv -e .env.test -- npm run test
      "

  db-test:
    image: postgres:17
    restart: always
    logging:
      driver: none
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test-fluxogramas-interativos
    ports:
      - "2344:5432"
