version: "3.8"

services:
  server:
    image: server-image
    container_name: server-container
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env.development
    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"
    depends_on:
      - db
    volumes:
      - ..:/app
    command: "sh docker/scripts/run-development.sh"

  db:
    image: postgres:17
    container_name: db-container
    restart: always
    logging:
      driver: none
    env_file:
      - ../.env.development
    ports:
      - "2345:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
